# Generated by Django 5.1.6 on 2025-03-07 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0002_category_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Courses',
        ),
    ]
