# Generated by Django 5.1.6 on 2025-03-07 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0004_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='elearning.category'),
        ),
    ]
