# Generated by Django 5.1.6 on 2025-03-16 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0007_courses_top_cousrses'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='trending',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
