# Generated by Django 5.1.6 on 2025-03-19 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0010_trend_trend'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='price',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
