# Generated by Django 5.1.6 on 2025-03-19 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0011_courses_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='top_cousrses',
        ),
    ]
