# Generated by Django 5.1.6 on 2025-03-21 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0012_remove_courses_top_cousrses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
            ],
        ),
    ]
