# Generated by Django 5.1.6 on 2025-03-24 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0014_remove_courses_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
