# Generated by Django 5.1.6 on 2025-03-24 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0015_courses_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='is_paid',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
