# Generated by Django 5.1.6 on 2025-03-25 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0016_courses_is_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elearning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('favicon', models.FileField(null=True, upload_to='static/uploads')),
            ],
        ),
    ]
