# Generated by Django 5.1.6 on 2025-03-26 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0017_elearning'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Elearning',
        ),
    ]
