# Generated by Django 5.1.6 on 2025-03-06 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfvideo',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='static/pdfvideo'),
        ),
        migrations.AlterField(
            model_name='pdfvideo',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='static/pdfvideo'),
        ),
    ]
