# Generated by Django 5.1.6 on 2025-03-06 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpages', '0002_alter_pdfvideo_pdf_file_alter_pdfvideo_video_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='static/pdfvideo')),
            ],
        ),
        migrations.DeleteModel(
            name='PdfVideo',
        ),
    ]
