# Generated by Django 5.1.6 on 2025-03-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpages', '0003_pdf_delete_pdfvideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='static/pdfvideo')),
            ],
        ),
    ]
