# Generated by Django 5.1.6 on 2025-03-07 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpages', '0005_pdf_django_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='django_video',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
