# Generated by Django 5.1.6 on 2025-03-07 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpages', '0006_video_django_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='created_at',
            field=models.DateTimeField(default=True),
        ),
    ]
