# Generated by Django 5.1.6 on 2025-03-07 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpages', '0007_pdf_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdf',
            name='created_at',
        ),
    ]
