# Generated by Django 5.1.6 on 2025-03-10 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0005_courses_category'),
        ('userpages', '0013_video_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='courses',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='elearning.courses'),
        ),
    ]
