# Generated by Django 5.1.6 on 2025-03-10 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0005_courses_category'),
        ('userpages', '0014_video_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='courses',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='elearning.courses'),
        ),
    ]
