# Generated by Django 5.1.6 on 2025-03-11 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpages', '0016_assignment'),
        ('userpages', '0016_notice'),
    ]

    operations = [
    ]
