# Generated by Django 5.1.6 on 2025-03-11 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpages', '0017_merge_0016_assignment_0016_notice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Assignment',
        ),
    ]
