# Generated by Django 5.1.6 on 2025-03-11 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpages', '0019_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='static/Assignment'),
        ),
    ]
