# Generated by Django 5.1.6 on 2025-03-11 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpages', '0021_submission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='student',
        ),
    ]
