# Generated by Django 5.1.6 on 2025-03-16 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0006_courses_users'),
        ('userpages', '0027_remove_submission_submitted_by_alter_submission_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='description',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='assigned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='courses',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='pdf_file',
            field=models.FileField(upload_to='assignments/'),
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
        migrations.AddField(
            model_name='assignment',
            name='courses',
            field=models.ManyToManyField(to='elearning.courses'),
        ),
    ]
