# Generated by Django 5.1.6 on 2025-03-16 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpages', '0029_submission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='user',
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
