# Generated by Django 5.1.6 on 2025-03-16 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpages', '0032_submission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='static/staff')),
                ('name', models.CharField(max_length=200)),
                ('post', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
    ]
