# Generated by Django 5.1.6 on 2025-03-20 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0012_remove_courses_top_cousrses'),
        ('userpages', '0035_remove_video_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to='elearning.courses'),
            preserve_default=False,
        ),
    ]
