# Generated by Django 5.1.6 on 2025-03-20 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0012_remove_courses_top_cousrses'),
        ('userpages', '0036_pdf_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdf',
            name='course',
        ),
        migrations.AddField(
            model_name='video',
            name='courses',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='elearning.courses'),
        ),
    ]
