# Generated by Django 5.1.6 on 2025-03-20 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0012_remove_courses_top_cousrses'),
        ('userpages', '0037_remove_pdf_course_video_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='courses',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='elearning.courses'),
        ),
    ]
