# Generated by Django 5.1.6 on 2025-03-20 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpages', '0038_pdf_courses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='video_file',
            new_name='video',
        ),
    ]
