# Generated by Django 5.1.6 on 2025-03-20 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpages', '0039_rename_video_file_video_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='video',
            new_name='video_file',
        ),
    ]
