# Generated by Django 5.1.6 on 2025-03-20 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpages', '0040_rename_video_video_video_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
