# Generated by Django 5.1.6 on 2025-03-20 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0012_remove_courses_top_cousrses'),
        ('userpages', '0041_delete_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='static/pdfvideo')),
                ('django_video', models.BooleanField(blank=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='elearning.category')),
                ('courses', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='elearning.courses')),
            ],
        ),
    ]
