# Generated by Django 5.1.6 on 2025-03-20 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpages', '0042_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
