# Generated by Django 5.1.6 on 2025-03-22 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpages', '0043_delete_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='mark',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
