# Generated by Django 5.1.6 on 2025-03-23 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpages', '0045_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
