# Generated by Django 5.1.6 on 2025-03-23 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpages', '0049_transaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
