# Generated by Django 5.1.6 on 2025-03-24 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpages', '0053_transaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
