# Generated by Django 5.1.6 on 2025-03-24 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpages', '0055_transaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
