# Generated by Django 5.1.6 on 2025-03-24 12:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0016_courses_is_paid'),
        ('userpages', '0056_delete_transaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('amount', models.FloatField()),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('esewa', 'Esewa'), ('card', 'Card')], max_length=10)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('phone_no', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(15)])),
                ('address', models.CharField(max_length=200)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('payment_details', models.TextField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearning.courses')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
